# User.create(first_name: "Nolan",
#             last_name: "Frazier",
#             profile_name: "nofrazier",
#             email: "frazier103@gmail.com",
#             password: "Osborne1988",
#             password_confirmation: "Osborne1988",
#             admin: true,
#             activated: true,
#             activated_at: Time.zone.now)
